package com.market.dao;

import com.market.domain.BasicData;
import java.util.List;

public interface BasicDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    int insert(BasicData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    List<BasicData> selectAll();
}