package com.market.dao;

import com.market.domain.CommisionConfiguration;
import java.util.List;

public interface CommisionConfigurationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commision_configuration
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commision_configuration
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    int insert(CommisionConfiguration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commision_configuration
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    CommisionConfiguration selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commision_configuration
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    List<CommisionConfiguration> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commision_configuration
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    int updateByPrimaryKey(CommisionConfiguration record);
}