package com.market.dao;

import com.market.domain.CommisionRecord;
import java.util.List;

public interface CommisionRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commision_record
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commision_record
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int insert(CommisionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commision_record
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    CommisionRecord selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commision_record
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    List<CommisionRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commision_record
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int updateByPrimaryKey(CommisionRecord record);
}