package com.market.dao;

import com.market.domain.ConsumptionRecord;
import java.util.List;

public interface ConsumptionRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_record
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_record
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int insert(ConsumptionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_record
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    ConsumptionRecord selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_record
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    List<ConsumptionRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_record
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int updateByPrimaryKey(ConsumptionRecord record);
}