package com.market.dao;

import com.market.domain.ConsumptionRecord;
import java.util.List;

public interface ConsumptionRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_record
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_record
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    int insert(ConsumptionRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_record
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    ConsumptionRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_record
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    List<ConsumptionRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumption_record
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    int updateByPrimaryKey(ConsumptionRecord record);
}