package com.market.dao;

import com.market.domain.GoodsProductRelation;
import java.util.List;

public interface GoodsProductRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_product_relation
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_product_relation
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int insert(GoodsProductRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_product_relation
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    GoodsProductRelation selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_product_relation
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    List<GoodsProductRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_product_relation
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int updateByPrimaryKey(GoodsProductRelation record);
}