package com.market.dao;

import com.market.domain.GoodsImageRelation;
import java.util.List;

public interface GoodsImageRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_image_relation
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_image_relation
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int insert(GoodsImageRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_image_relation
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    GoodsImageRelation selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_image_relation
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    List<GoodsImageRelation> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_image_relation
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int updateByPrimaryKey(GoodsImageRelation record);
}