package com.market.dao;

import com.market.domain.OrderInfluence;
import java.util.List;

public interface OrderInfluenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_influence
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_influence
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int insert(OrderInfluence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_influence
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    OrderInfluence selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_influence
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    List<OrderInfluence> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_influence
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int updateByPrimaryKey(OrderInfluence record);
}