package com.market.dao;

import com.market.domain.Sales;
import java.util.List;

public interface SalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int insert(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    Sales selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    List<Sales> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int updateByPrimaryKey(Sales record);
}