package com.market.dao;

import com.market.domain.SalesApply;
import java.util.List;

public interface SalesApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_apply
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int deleteByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_apply
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int insert(SalesApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_apply
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    SalesApply selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_apply
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    List<SalesApply> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales_apply
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    int updateByPrimaryKey(SalesApply record);
}