package com.market.dao;

import com.market.domain.ShoppingTicket;
import java.util.List;

public interface ShoppingTicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_ticket
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_ticket
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    int insert(ShoppingTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_ticket
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    ShoppingTicket selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_ticket
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    List<ShoppingTicket> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_ticket
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    int updateByPrimaryKey(ShoppingTicket record);
}