package com.market.domain;

public class BasicData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data.domain
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data.code
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Short code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data.label
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data.description
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data.domain
     *
     * @return the value of basic_data.domain
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data.domain
     *
     * @param domain the value for basic_data.domain
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data.code
     *
     * @return the value of basic_data.code
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Short getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data.code
     *
     * @param code the value for basic_data.code
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCode(Short code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data.label
     *
     * @return the value of basic_data.label
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data.label
     *
     * @param label the value for basic_data.label
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data.description
     *
     * @return the value of basic_data.description
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data.description
     *
     * @param description the value for basic_data.description
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setDescription(String description) {
        this.description = description;
    }
}