package com.market.domain;

import java.util.Date;

public class CommisionWithdrawApply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_withdraw_apply.id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_withdraw_apply.money
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_withdraw_apply.applicant_type
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Long applicantType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_withdraw_apply.applicant_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Object applicantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_withdraw_apply.collect_type
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Long collectType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_withdraw_apply.bank_card_number
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private String bankCardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_withdraw_apply.bank_card_name
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private String bankCardName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_withdraw_apply.receiver_name
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_withdraw_apply.status
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Long status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_withdraw_apply.create_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_withdraw_apply.create_by
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_withdraw_apply.update_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_withdraw_apply.update_by
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_withdraw_apply.id
     *
     * @return the value of commision_withdraw_apply.id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_withdraw_apply.id
     *
     * @param id the value for commision_withdraw_apply.id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_withdraw_apply.money
     *
     * @return the value of commision_withdraw_apply.money
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_withdraw_apply.money
     *
     * @param money the value for commision_withdraw_apply.money
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_withdraw_apply.applicant_type
     *
     * @return the value of commision_withdraw_apply.applicant_type
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Long getApplicantType() {
        return applicantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_withdraw_apply.applicant_type
     *
     * @param applicantType the value for commision_withdraw_apply.applicant_type
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setApplicantType(Long applicantType) {
        this.applicantType = applicantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_withdraw_apply.applicant_id
     *
     * @return the value of commision_withdraw_apply.applicant_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Object getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_withdraw_apply.applicant_id
     *
     * @param applicantId the value for commision_withdraw_apply.applicant_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setApplicantId(Object applicantId) {
        this.applicantId = applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_withdraw_apply.collect_type
     *
     * @return the value of commision_withdraw_apply.collect_type
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Long getCollectType() {
        return collectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_withdraw_apply.collect_type
     *
     * @param collectType the value for commision_withdraw_apply.collect_type
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setCollectType(Long collectType) {
        this.collectType = collectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_withdraw_apply.bank_card_number
     *
     * @return the value of commision_withdraw_apply.bank_card_number
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public String getBankCardNumber() {
        return bankCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_withdraw_apply.bank_card_number
     *
     * @param bankCardNumber the value for commision_withdraw_apply.bank_card_number
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setBankCardNumber(String bankCardNumber) {
        this.bankCardNumber = bankCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_withdraw_apply.bank_card_name
     *
     * @return the value of commision_withdraw_apply.bank_card_name
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public String getBankCardName() {
        return bankCardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_withdraw_apply.bank_card_name
     *
     * @param bankCardName the value for commision_withdraw_apply.bank_card_name
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setBankCardName(String bankCardName) {
        this.bankCardName = bankCardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_withdraw_apply.receiver_name
     *
     * @return the value of commision_withdraw_apply.receiver_name
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_withdraw_apply.receiver_name
     *
     * @param receiverName the value for commision_withdraw_apply.receiver_name
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_withdraw_apply.status
     *
     * @return the value of commision_withdraw_apply.status
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Long getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_withdraw_apply.status
     *
     * @param status the value for commision_withdraw_apply.status
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setStatus(Long status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_withdraw_apply.create_time
     *
     * @return the value of commision_withdraw_apply.create_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_withdraw_apply.create_time
     *
     * @param createTime the value for commision_withdraw_apply.create_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_withdraw_apply.create_by
     *
     * @return the value of commision_withdraw_apply.create_by
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_withdraw_apply.create_by
     *
     * @param createBy the value for commision_withdraw_apply.create_by
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_withdraw_apply.update_time
     *
     * @return the value of commision_withdraw_apply.update_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_withdraw_apply.update_time
     *
     * @param updateTime the value for commision_withdraw_apply.update_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_withdraw_apply.update_by
     *
     * @return the value of commision_withdraw_apply.update_by
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_withdraw_apply.update_by
     *
     * @param updateBy the value for commision_withdraw_apply.update_by
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }
}