package com.market.domain;

import java.util.Date;

public class CommisionRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_record.id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_record.applicant_type
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Long applicantType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_record.applicant_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Object applicantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_record.number
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Double number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_record.order_detail_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Object orderDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_record.create_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_record.id
     *
     * @return the value of commision_record.id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_record.id
     *
     * @param id the value for commision_record.id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_record.applicant_type
     *
     * @return the value of commision_record.applicant_type
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Long getApplicantType() {
        return applicantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_record.applicant_type
     *
     * @param applicantType the value for commision_record.applicant_type
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setApplicantType(Long applicantType) {
        this.applicantType = applicantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_record.applicant_id
     *
     * @return the value of commision_record.applicant_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Object getApplicantId() {
        return applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_record.applicant_id
     *
     * @param applicantId the value for commision_record.applicant_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setApplicantId(Object applicantId) {
        this.applicantId = applicantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_record.number
     *
     * @return the value of commision_record.number
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Double getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_record.number
     *
     * @param number the value for commision_record.number
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setNumber(Double number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_record.order_detail_id
     *
     * @return the value of commision_record.order_detail_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Object getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_record.order_detail_id
     *
     * @param orderDetailId the value for commision_record.order_detail_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setOrderDetailId(Object orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_record.create_time
     *
     * @return the value of commision_record.create_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_record.create_time
     *
     * @param createTime the value for commision_record.create_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}