package com.market.domain;

import java.util.Date;

public class CommisionConfiguration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_configuration.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_configuration.target_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Short targetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_configuration.target_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_configuration.calculate_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Short calculateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_configuration.calculate_value
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Double calculateValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_configuration.goods_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Object goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_configuration.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_configuration.create_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_configuration.update_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_configuration.update_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_configuration.is_deleted
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Boolean isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_configuration.min_sales
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Short minSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_configuration.max_sales
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Short maxSales;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_configuration.id
     *
     * @return the value of commision_configuration.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_configuration.id
     *
     * @param id the value for commision_configuration.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_configuration.target_type
     *
     * @return the value of commision_configuration.target_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Short getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_configuration.target_type
     *
     * @param targetType the value for commision_configuration.target_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setTargetType(Short targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_configuration.target_id
     *
     * @return the value of commision_configuration.target_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_configuration.target_id
     *
     * @param targetId the value for commision_configuration.target_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setTargetId(String targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_configuration.calculate_type
     *
     * @return the value of commision_configuration.calculate_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Short getCalculateType() {
        return calculateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_configuration.calculate_type
     *
     * @param calculateType the value for commision_configuration.calculate_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCalculateType(Short calculateType) {
        this.calculateType = calculateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_configuration.calculate_value
     *
     * @return the value of commision_configuration.calculate_value
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Double getCalculateValue() {
        return calculateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_configuration.calculate_value
     *
     * @param calculateValue the value for commision_configuration.calculate_value
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCalculateValue(Double calculateValue) {
        this.calculateValue = calculateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_configuration.goods_id
     *
     * @return the value of commision_configuration.goods_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Object getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_configuration.goods_id
     *
     * @param goodsId the value for commision_configuration.goods_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setGoodsId(Object goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_configuration.create_time
     *
     * @return the value of commision_configuration.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_configuration.create_time
     *
     * @param createTime the value for commision_configuration.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_configuration.create_by
     *
     * @return the value of commision_configuration.create_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_configuration.create_by
     *
     * @param createBy the value for commision_configuration.create_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_configuration.update_time
     *
     * @return the value of commision_configuration.update_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_configuration.update_time
     *
     * @param updateTime the value for commision_configuration.update_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_configuration.update_by
     *
     * @return the value of commision_configuration.update_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_configuration.update_by
     *
     * @param updateBy the value for commision_configuration.update_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_configuration.is_deleted
     *
     * @return the value of commision_configuration.is_deleted
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_configuration.is_deleted
     *
     * @param isDeleted the value for commision_configuration.is_deleted
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_configuration.min_sales
     *
     * @return the value of commision_configuration.min_sales
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Short getMinSales() {
        return minSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_configuration.min_sales
     *
     * @param minSales the value for commision_configuration.min_sales
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setMinSales(Short minSales) {
        this.minSales = minSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_configuration.max_sales
     *
     * @return the value of commision_configuration.max_sales
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Short getMaxSales() {
        return maxSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_configuration.max_sales
     *
     * @param maxSales the value for commision_configuration.max_sales
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setMaxSales(Short maxSales) {
        this.maxSales = maxSales;
    }
}