package com.market.domain;

import java.util.Date;

public class CommisionRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_record.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_record.applicant_type
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Short applicantType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_record.applicant_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String applicationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_record.number
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Double number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_record.order_detail_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String orderDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commision_record.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_record.id
     *
     * @return the value of commision_record.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_record.id
     *
     * @param id the value for commision_record.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_record.applicant_type
     *
     * @return the value of commision_record.applicant_type
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Short getApplicantType() {
        return applicantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_record.applicant_type
     *
     * @param applicantType the value for commision_record.applicant_type
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setApplicantType(Short applicantType) {
        this.applicantType = applicantType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_record.applicant_id
     *
     * @return the value of commision_record.applicant_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_record.applicant_id
     *
     * @param applicationId the value for commision_record.applicant_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_record.number
     *
     * @return the value of commision_record.number
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Double getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_record.number
     *
     * @param number the value for commision_record.number
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setNumber(Double number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_record.order_detail_id
     *
     * @return the value of commision_record.order_detail_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_record.order_detail_id
     *
     * @param orderDetailId the value for commision_record.order_detail_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setOrderDetailId(String orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commision_record.create_time
     *
     * @return the value of commision_record.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commision_record.create_time
     *
     * @param createTime the value for commision_record.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}