package com.market.domain;

import java.util.Date;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.name
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.status
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.create_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.update_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.update_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.password
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.fund
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Double fund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.freezed_fund
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Double freezedFund;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.id
     *
     * @return the value of company.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.id
     *
     * @param id the value for company.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.name
     *
     * @return the value of company.name
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.name
     *
     * @param name the value for company.name
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.status
     *
     * @return the value of company.status
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.status
     *
     * @param status the value for company.status
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.create_time
     *
     * @return the value of company.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.create_time
     *
     * @param createTime the value for company.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.create_by
     *
     * @return the value of company.create_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.create_by
     *
     * @param createBy the value for company.create_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.update_time
     *
     * @return the value of company.update_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.update_time
     *
     * @param updateTime the value for company.update_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.update_by
     *
     * @return the value of company.update_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.update_by
     *
     * @param updateBy the value for company.update_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.password
     *
     * @return the value of company.password
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.password
     *
     * @param password the value for company.password
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.fund
     *
     * @return the value of company.fund
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Double getFund() {
        return fund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.fund
     *
     * @param fund the value for company.fund
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setFund(Double fund) {
        this.fund = fund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.freezed_fund
     *
     * @return the value of company.freezed_fund
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Double getFreezedFund() {
        return freezedFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.freezed_fund
     *
     * @param freezedFund the value for company.freezed_fund
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setFreezedFund(Double freezedFund) {
        this.freezedFund = freezedFund;
    }
}