package com.market.domain;

import java.util.Date;

public class DiscountCodeConfiguration {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration.code
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration.to_user
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String toUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration.upper_limit
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Integer upperLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration.stock
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration.caculate_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Short caculateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration.dead_line
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Date deadLine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration.status
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration.create_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String createBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration.id
     *
     * @return the value of discount_code_configuration.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration.id
     *
     * @param id the value for discount_code_configuration.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration.code
     *
     * @return the value of discount_code_configuration.code
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration.code
     *
     * @param code the value for discount_code_configuration.code
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration.to_user
     *
     * @return the value of discount_code_configuration.to_user
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getToUser() {
        return toUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration.to_user
     *
     * @param toUser the value for discount_code_configuration.to_user
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setToUser(String toUser) {
        this.toUser = toUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration.upper_limit
     *
     * @return the value of discount_code_configuration.upper_limit
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Integer getUpperLimit() {
        return upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration.upper_limit
     *
     * @param upperLimit the value for discount_code_configuration.upper_limit
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setUpperLimit(Integer upperLimit) {
        this.upperLimit = upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration.stock
     *
     * @return the value of discount_code_configuration.stock
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration.stock
     *
     * @param stock the value for discount_code_configuration.stock
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration.caculate_type
     *
     * @return the value of discount_code_configuration.caculate_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Short getCaculateType() {
        return caculateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration.caculate_type
     *
     * @param caculateType the value for discount_code_configuration.caculate_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCaculateType(Short caculateType) {
        this.caculateType = caculateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration.dead_line
     *
     * @return the value of discount_code_configuration.dead_line
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Date getDeadLine() {
        return deadLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration.dead_line
     *
     * @param deadLine the value for discount_code_configuration.dead_line
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setDeadLine(Date deadLine) {
        this.deadLine = deadLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration.status
     *
     * @return the value of discount_code_configuration.status
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration.status
     *
     * @param status the value for discount_code_configuration.status
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration.create_time
     *
     * @return the value of discount_code_configuration.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration.create_time
     *
     * @param createTime the value for discount_code_configuration.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration.create_by
     *
     * @return the value of discount_code_configuration.create_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration.create_by
     *
     * @param createBy the value for discount_code_configuration.create_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
}