package com.market.domain;

public class DiscountCodeConfigurationDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration_detail.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration_detail.discount_code_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String discountCodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration_detail.goods_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration_detail.caculate_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Short caculateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration_detail.caculate_value
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Double caculateValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration_detail.discount_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Short discountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discount_code_configuration_detail.discount_value
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Double discountValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration_detail.id
     *
     * @return the value of discount_code_configuration_detail.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration_detail.id
     *
     * @param id the value for discount_code_configuration_detail.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration_detail.discount_code_id
     *
     * @return the value of discount_code_configuration_detail.discount_code_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getDiscountCodeId() {
        return discountCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration_detail.discount_code_id
     *
     * @param discountCodeId the value for discount_code_configuration_detail.discount_code_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setDiscountCodeId(String discountCodeId) {
        this.discountCodeId = discountCodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration_detail.goods_id
     *
     * @return the value of discount_code_configuration_detail.goods_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration_detail.goods_id
     *
     * @param goodsId the value for discount_code_configuration_detail.goods_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration_detail.caculate_type
     *
     * @return the value of discount_code_configuration_detail.caculate_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Short getCaculateType() {
        return caculateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration_detail.caculate_type
     *
     * @param caculateType the value for discount_code_configuration_detail.caculate_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCaculateType(Short caculateType) {
        this.caculateType = caculateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration_detail.caculate_value
     *
     * @return the value of discount_code_configuration_detail.caculate_value
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Double getCaculateValue() {
        return caculateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration_detail.caculate_value
     *
     * @param caculateValue the value for discount_code_configuration_detail.caculate_value
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCaculateValue(Double caculateValue) {
        this.caculateValue = caculateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration_detail.discount_type
     *
     * @return the value of discount_code_configuration_detail.discount_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Short getDiscountType() {
        return discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration_detail.discount_type
     *
     * @param discountType the value for discount_code_configuration_detail.discount_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setDiscountType(Short discountType) {
        this.discountType = discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discount_code_configuration_detail.discount_value
     *
     * @return the value of discount_code_configuration_detail.discount_value
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Double getDiscountValue() {
        return discountValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discount_code_configuration_detail.discount_value
     *
     * @param discountValue the value for discount_code_configuration_detail.discount_value
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setDiscountValue(Double discountValue) {
        this.discountValue = discountValue;
    }
}