package com.market.domain;

import java.util.Date;

public class GoodsImageRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_image_relation.id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_image_relation.goods_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Object goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_image_relation.image_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Object imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_image_relation.create_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_image_relation.is_deleted
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_image_relation.id
     *
     * @return the value of goods_image_relation.id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_image_relation.id
     *
     * @param id the value for goods_image_relation.id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_image_relation.goods_id
     *
     * @return the value of goods_image_relation.goods_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Object getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_image_relation.goods_id
     *
     * @param goodsId the value for goods_image_relation.goods_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setGoodsId(Object goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_image_relation.image_id
     *
     * @return the value of goods_image_relation.image_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Object getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_image_relation.image_id
     *
     * @param imageId the value for goods_image_relation.image_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setImageId(Object imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_image_relation.create_time
     *
     * @return the value of goods_image_relation.create_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_image_relation.create_time
     *
     * @param createTime the value for goods_image_relation.create_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_image_relation.is_deleted
     *
     * @return the value of goods_image_relation.is_deleted
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_image_relation.is_deleted
     *
     * @param isDeleted the value for goods_image_relation.is_deleted
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}