package com.market.domain;

import java.util.Date;

public class GoodsProductRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_product_relation.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_product_relation.goods_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_product_relation.product_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_product_relation.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_product_relation.is_deleted
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_product_relation.id
     *
     * @return the value of goods_product_relation.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_product_relation.id
     *
     * @param id the value for goods_product_relation.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_product_relation.goods_id
     *
     * @return the value of goods_product_relation.goods_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_product_relation.goods_id
     *
     * @param goodsId the value for goods_product_relation.goods_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_product_relation.product_id
     *
     * @return the value of goods_product_relation.product_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_product_relation.product_id
     *
     * @param productId the value for goods_product_relation.product_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_product_relation.create_time
     *
     * @return the value of goods_product_relation.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_product_relation.create_time
     *
     * @param createTime the value for goods_product_relation.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_product_relation.is_deleted
     *
     * @return the value of goods_product_relation.is_deleted
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_product_relation.is_deleted
     *
     * @param isDeleted the value for goods_product_relation.is_deleted
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}