package com.market.domain;

import java.util.Date;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.file_name
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.suffix
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String suffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.relative_path
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String relativePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.create_by
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.is_deleted
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.file_name
     *
     * @return the value of image.file_name
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.file_name
     *
     * @param fileName the value for image.file_name
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.suffix
     *
     * @return the value of image.suffix
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.suffix
     *
     * @param suffix the value for image.suffix
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.relative_path
     *
     * @return the value of image.relative_path
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getRelativePath() {
        return relativePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.relative_path
     *
     * @param relativePath the value for image.relative_path
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setRelativePath(String relativePath) {
        this.relativePath = relativePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.create_time
     *
     * @return the value of image.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.create_time
     *
     * @param createTime the value for image.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.create_by
     *
     * @return the value of image.create_by
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.create_by
     *
     * @param createBy the value for image.create_by
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.is_deleted
     *
     * @return the value of image.is_deleted
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.is_deleted
     *
     * @param isDeleted the value for image.is_deleted
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}