package com.market.domain;

public class OrderInfluence {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_influence.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_influence.order_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_influence.influence_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Short influenceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_influence.influence_value
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Double influenceValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_influence.id
     *
     * @return the value of order_influence.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_influence.id
     *
     * @param id the value for order_influence.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_influence.order_id
     *
     * @return the value of order_influence.order_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_influence.order_id
     *
     * @param orderId the value for order_influence.order_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_influence.influence_type
     *
     * @return the value of order_influence.influence_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Short getInfluenceType() {
        return influenceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_influence.influence_type
     *
     * @param influenceType the value for order_influence.influence_type
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setInfluenceType(Short influenceType) {
        this.influenceType = influenceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_influence.influence_value
     *
     * @return the value of order_influence.influence_value
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Double getInfluenceValue() {
        return influenceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_influence.influence_value
     *
     * @param influenceValue the value for order_influence.influence_value
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setInfluenceValue(Double influenceValue) {
        this.influenceValue = influenceValue;
    }
}