package com.market.domain;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.order_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.goods_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.price
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.quantity
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Short quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.total_price
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Double totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.original_price
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Double originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.goods_name
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.image_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String imageId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.id
     *
     * @return the value of order_detail.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.id
     *
     * @param id the value for order_detail.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.order_id
     *
     * @return the value of order_detail.order_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.order_id
     *
     * @param orderId the value for order_detail.order_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.goods_id
     *
     * @return the value of order_detail.goods_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.goods_id
     *
     * @param goodsId the value for order_detail.goods_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.price
     *
     * @return the value of order_detail.price
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.price
     *
     * @param price the value for order_detail.price
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.quantity
     *
     * @return the value of order_detail.quantity
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Short getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.quantity
     *
     * @param quantity the value for order_detail.quantity
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setQuantity(Short quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.total_price
     *
     * @return the value of order_detail.total_price
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.total_price
     *
     * @param totalPrice the value for order_detail.total_price
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.original_price
     *
     * @return the value of order_detail.original_price
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Double getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.original_price
     *
     * @param originalPrice the value for order_detail.original_price
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setOriginalPrice(Double originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.goods_name
     *
     * @return the value of order_detail.goods_name
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.goods_name
     *
     * @param goodsName the value for order_detail.goods_name
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.image_id
     *
     * @return the value of order_detail.image_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.image_id
     *
     * @param imageId the value for order_detail.image_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setImageId(String imageId) {
        this.imageId = imageId;
    }
}