package com.market.domain;

import java.util.Date;

public class PayRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.order_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.order_code
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String orderCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.total_price
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Double totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_record.is_success
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Boolean isSuccess;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.id
     *
     * @return the value of pay_record.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.id
     *
     * @param id the value for pay_record.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.order_id
     *
     * @return the value of pay_record.order_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.order_id
     *
     * @param orderId the value for pay_record.order_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.order_code
     *
     * @return the value of pay_record.order_code
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.order_code
     *
     * @param orderCode the value for pay_record.order_code
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.total_price
     *
     * @return the value of pay_record.total_price
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.total_price
     *
     * @param totalPrice the value for pay_record.total_price
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.create_time
     *
     * @return the value of pay_record.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.create_time
     *
     * @param createTime the value for pay_record.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_record.is_success
     *
     * @return the value of pay_record.is_success
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Boolean getIsSuccess() {
        return isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_record.is_success
     *
     * @param isSuccess the value for pay_record.is_success
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setIsSuccess(Boolean isSuccess) {
        this.isSuccess = isSuccess;
    }
}