package com.market.domain;

import java.util.Date;

public class SalesApply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_apply.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_apply.user_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_apply.name
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_apply.mobile_number
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String mobileNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_apply.comment
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_apply.company_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_apply.status
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_apply.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_apply.update_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_apply.handler_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private String handlerBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_apply.is_deleted
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    private Boolean isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_apply.id
     *
     * @return the value of sales_apply.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_apply.id
     *
     * @param id the value for sales_apply.id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_apply.user_id
     *
     * @return the value of sales_apply.user_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_apply.user_id
     *
     * @param userId the value for sales_apply.user_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_apply.name
     *
     * @return the value of sales_apply.name
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_apply.name
     *
     * @param name the value for sales_apply.name
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_apply.mobile_number
     *
     * @return the value of sales_apply.mobile_number
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_apply.mobile_number
     *
     * @param mobileNumber the value for sales_apply.mobile_number
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_apply.comment
     *
     * @return the value of sales_apply.comment
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_apply.comment
     *
     * @param comment the value for sales_apply.comment
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_apply.company_id
     *
     * @return the value of sales_apply.company_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_apply.company_id
     *
     * @param companyId the value for sales_apply.company_id
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_apply.status
     *
     * @return the value of sales_apply.status
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_apply.status
     *
     * @param status the value for sales_apply.status
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_apply.create_time
     *
     * @return the value of sales_apply.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_apply.create_time
     *
     * @param createTime the value for sales_apply.create_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_apply.update_time
     *
     * @return the value of sales_apply.update_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_apply.update_time
     *
     * @param updateTime the value for sales_apply.update_time
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_apply.handler_by
     *
     * @return the value of sales_apply.handler_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public String getHandlerBy() {
        return handlerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_apply.handler_by
     *
     * @param handlerBy the value for sales_apply.handler_by
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setHandlerBy(String handlerBy) {
        this.handlerBy = handlerBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_apply.is_deleted
     *
     * @return the value of sales_apply.is_deleted
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_apply.is_deleted
     *
     * @param isDeleted the value for sales_apply.is_deleted
     *
     * @mbg.generated Mon Mar 27 01:56:44 CST 2017
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }
}