package com.market.domain;

import java.util.Date;

public class Sales {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Object id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.name
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.user_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Object userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.company_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Object companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.mobile_number
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private String mobileNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.commision
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Double commision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.freezed_commision
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Double freezedCommision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.status
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.create_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.id
     *
     * @return the value of sales.id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Object getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.id
     *
     * @param id the value for sales.id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setId(Object id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.name
     *
     * @return the value of sales.name
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.name
     *
     * @param name the value for sales.name
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.user_id
     *
     * @return the value of sales.user_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Object getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.user_id
     *
     * @param userId the value for sales.user_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setUserId(Object userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.company_id
     *
     * @return the value of sales.company_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Object getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.company_id
     *
     * @param companyId the value for sales.company_id
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setCompanyId(Object companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.mobile_number
     *
     * @return the value of sales.mobile_number
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.mobile_number
     *
     * @param mobileNumber the value for sales.mobile_number
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.commision
     *
     * @return the value of sales.commision
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Double getCommision() {
        return commision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.commision
     *
     * @param commision the value for sales.commision
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setCommision(Double commision) {
        this.commision = commision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.freezed_commision
     *
     * @return the value of sales.freezed_commision
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Double getFreezedCommision() {
        return freezedCommision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.freezed_commision
     *
     * @param freezedCommision the value for sales.freezed_commision
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setFreezedCommision(Double freezedCommision) {
        this.freezedCommision = freezedCommision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.status
     *
     * @return the value of sales.status
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.status
     *
     * @param status the value for sales.status
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.create_time
     *
     * @return the value of sales.create_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.create_time
     *
     * @param createTime the value for sales.create_time
     *
     * @mbg.generated Thu Mar 23 23:09:31 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}