package com.market.domain;

import java.util.Date;

public class shopAssistant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_assistant.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_assistant.name
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_assistant.mobile_number
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String mobileNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_assistant.user_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_assistant.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_assistant.create_by
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_assistant.update_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_assistant.update_by
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_assistant.status
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_assistant.id
     *
     * @return the value of shop_assistant.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_assistant.id
     *
     * @param id the value for shop_assistant.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_assistant.name
     *
     * @return the value of shop_assistant.name
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_assistant.name
     *
     * @param name the value for shop_assistant.name
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_assistant.mobile_number
     *
     * @return the value of shop_assistant.mobile_number
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_assistant.mobile_number
     *
     * @param mobileNumber the value for shop_assistant.mobile_number
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_assistant.user_id
     *
     * @return the value of shop_assistant.user_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_assistant.user_id
     *
     * @param userId the value for shop_assistant.user_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_assistant.create_time
     *
     * @return the value of shop_assistant.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_assistant.create_time
     *
     * @param createTime the value for shop_assistant.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_assistant.create_by
     *
     * @return the value of shop_assistant.create_by
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_assistant.create_by
     *
     * @param createBy the value for shop_assistant.create_by
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_assistant.update_time
     *
     * @return the value of shop_assistant.update_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_assistant.update_time
     *
     * @param updateTime the value for shop_assistant.update_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_assistant.update_by
     *
     * @return the value of shop_assistant.update_by
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_assistant.update_by
     *
     * @param updateBy the value for shop_assistant.update_by
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_assistant.status
     *
     * @return the value of shop_assistant.status
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_assistant.status
     *
     * @param status the value for shop_assistant.status
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}