package com.market.domain;

import java.util.Date;

public class ShoppingTicket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_ticket.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_ticket.order_detail_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String orderDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_ticket.status
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_ticket.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_ticket.product_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    private String productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_ticket.id
     *
     * @return the value of shopping_ticket.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_ticket.id
     *
     * @param id the value for shopping_ticket.id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_ticket.order_detail_id
     *
     * @return the value of shopping_ticket.order_detail_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_ticket.order_detail_id
     *
     * @param orderDetailId the value for shopping_ticket.order_detail_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setOrderDetailId(String orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_ticket.status
     *
     * @return the value of shopping_ticket.status
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_ticket.status
     *
     * @param status the value for shopping_ticket.status
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_ticket.create_time
     *
     * @return the value of shopping_ticket.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_ticket.create_time
     *
     * @param createTime the value for shopping_ticket.create_time
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_ticket.product_id
     *
     * @return the value of shopping_ticket.product_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_ticket.product_id
     *
     * @param productId the value for shopping_ticket.product_id
     *
     * @mbg.generated Sat Mar 25 19:15:36 CST 2017
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }
}